name: arabic_teacher_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  audioplayers: ^6.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.0
  rive: ^0.13.20
  # flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lesson_sample.json
    - assets/lesson_index.json
    - assets/lessons/
    - assets/images/
    - assets/animations/
